id: PC146E696
initial_creation_type: ocr
source_metadata:
  volumes:
    5413efada10146f2b96c5079c78ae440:
      base_file: v005.txt
      image_group_id: I1PD95850
      title: བདག་མེད་མ་ལྷ་མོ་བཅོ་ལྔ་ལ་བསྟོད་པ།
      total_pages: 2069
      volume_number: 5
