id: PC146E696
initial_creation_type: ocr
source_metadata:
  volumes:
    ceeb2df55e6f43698c746304f0c61e36:
      base_file: v042.txt
      image_group_id: I1PD95887
      title: བདག་མེད་མ་ལྷ་མོ་བཅོ་ལྔ་ལ་བསྟོད་པ།
      total_pages: 1712
      volume_number: 42
